add_newline = false
format = """ $time$directory$character"""
right_format = """$username$hostname$git_branch$git_status$cmd_duration"""

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = -1
style = "#fb4934 bold"
truncate_to_repo = true

[character]
format = "$symbol "
success_symbol = "[➜](bold white)"
error_symbol = "[➜](bold red)"

[time]
disabled = false
format = '\[[$time]($style)\] '
style = '#b8bb26 bold'

[username]
style_user = "#fabd2f"
style_root = "#fb4934"
format = "  [$user]($style) "
disabled = false
show_always = false

[hostname]
ssh_only = true
format = "at [$hostname](#8ec07c) "
disabled = false

[cmd_duration]
min_time = 100
format = "in [$duration](#83a598) "

[git_status]
disabled = false
style = '#fe8019'

[git_branch]
symbol = " "
style = '#fe8019'
format = 'on [$symbol$branch(:$remote_branch)]($style) '
#truncation_length = 15
